- ros_topic_name: "scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: BIDIRECTIONAL  # BIDIRECTIONAL or ROS_TO_GZ

- ros_topic_name: "lls_ir"
  gz_topic_name: "/lls_ir"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: BIDIRECTIONAL  # BIDIRECTIONAL or ROS_TO_GZ

- ros_topic_name: "lcs_ir"
  gz_topic_name: "/lcs_ir"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: BIDIRECTIONAL  # BIDIRECTIONAL or ROS_TO_GZ

- ros_topic_name: "cs_ir"
  gz_topic_name: "/cs_ir"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: BIDIRECTIONAL  # BIDIRECTIONAL or ROS_TO_GZ

- ros_topic_name: "rcs_ir"
  gz_topic_name: "/rcs_ir"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: BIDIRECTIONAL  # BIDIRECTIONAL or ROS_TO_GZ

- ros_topic_name: "rrs_ir"
  gz_topic_name: "/rrs_ir"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: BIDIRECTIONAL  # BIDIRECTIONAL or ROS_TO_GZ

- ros_topic_name: "cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: BIDIRECTIONAL  # BIDIRECTIONAL or ROS_TO_GZ